# Generated by Django 4.1.2 on 2022-11-19 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nmessages', '0001_initial'),
        ('project', '0001_initial'),
        ('targetusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILURE', 'Failure')], max_length=20)),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'Sms'), ('HTTP', 'Http'), ('SLACK', 'Slack')], max_length=20)),
                ('nmessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmessages.nmessage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILURE', 'Failure')], max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('notification_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILURE', 'Failure')], max_length=20)),
                ('request', models.JSONField()),
                ('response', models.JSONField()),
                ('notification_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationgroup')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targetusers.targetuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
