# Generated by Django 4.1.2 on 2022-11-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmessages', '0002_nmessage_notification_type'),
        ('project', '0002_project_data'),
        ('notifications', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationGroup',
            new_name='NotificationConfig',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_group',
            new_name='notification_config',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='notification_group',
            new_name='notification_config',
        ),
    ]
