# Generated by Django 4.1.2 on 2022-11-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_notificationgroup_notificationconfig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationconfig',
            name='status',
        ),
    ]
