# Generated by Django 4.1.2 on 2022-11-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notificationconfig_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_config',
        ),
    ]
