# Generated by Django 4.1.2 on 2022-11-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='request',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='response',
            field=models.JSONField(null=True),
        ),
    ]
