# Generated by Django 4.1.2 on 2022-12-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_notificationconfig_rrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.DateTimeField(),
        ),
    ]
