# Generated by Django 4.1.2 on 2022-12-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_alter_reservation_reserved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfig',
            name='mode',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('RESERVATION', 'Reservation')], default='RESERVATION', max_length=20),
        ),
    ]
