# Generated by Django 4.1.2 on 2022-12-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_notificationconfig_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
