# Generated by Django 4.1.2 on 2022-12-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmessages', '0005_nmessage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nmessage',
            old_name='content',
            new_name='data',
        ),
    ]
