# Generated by Django 4.1.2 on 2022-11-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('notification_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'Sms'), ('HTTP', 'Http'), ('SLACK', 'Slack')], max_length=32)),
                ('endpoint', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
