# Generated by Django 4.1.2 on 2022-12-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetusers', '0003_targetuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetuser',
            name='notification_type',
            field=models.CharField(choices=[('WEBHOOK', 'Webhook'), ('SLACK', 'Slack'), ('EMAIL', 'Email'), ('SMS', 'Sms')], max_length=32),
        ),
    ]
