name: Pylint

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd backend
          pipenv install --dev --deploy --system
      - name: Run pylint
        run: |
          cd backend
          PYTHONPATH=${PWD} DJANGO_SETTINGS_MODULE=noti_manager.settings pylint **/*.py --load-plugins pylint_django
